# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: validate_url 1.0.15 ruby lib

Gem::Specification.new do |s|
  s.name = "validate_url".freeze
  s.version = "1.0.15"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Tanel Suurhans".freeze, "Tarmo Lehtpuu".freeze, "Vladimir Krylov".freeze]
  s.date = "2022-05-13"
  s.description = "Library for validating urls in Rails.".freeze
  s.email = ["tanel.suurhans@perfectline.co".freeze, "tarmo.lehtpuu@perfectline.co".freeze, "vladimir.krylov@perfectline.co".freeze]
  s.extra_rdoc_files = [
    "LICENSE.md",
    "README.md"
  ]
  s.files = [
    "LICENSE.md",
    "README.md",
    "init.rb",
    "install.rb",
    "lib/locale/ar.yml",
    "lib/locale/de.yml",
    "lib/locale/en.yml",
    "lib/locale/es.yml",
    "lib/locale/fr.yml",
    "lib/locale/it.yml",
    "lib/locale/ja.yml",
    "lib/locale/km.yml",
    "lib/locale/nl.yml",
    "lib/locale/pl.yml",
    "lib/locale/pt-BR.yml",
    "lib/locale/pt-PT.yml",
    "lib/locale/pt.yml",
    "lib/locale/ro.yml",
    "lib/locale/ru.yml",
    "lib/locale/tr.yml",
    "lib/locale/vi.yml",
    "lib/locale/zh-CN.yml",
    "lib/locale/zh-TW.yml",
    "lib/validate_url.rb",
    "lib/validate_url/rspec_matcher.rb"
  ]
  s.homepage = "http://github.com/perfectline/validates_url/tree/master".freeze
  s.rubygems_version = "3.0.8".freeze
  s.summary = "Library for validating urls in Rails.".freeze
  s.specification_version = 4

  s.metadata = {
    "changelog_uri".freeze => "https://github.com/perfectline/validates_url/blob/master/CHANGELOG.md".freeze
  }

  s.add_dependency("activemodel", ">= 3.0.0")
  s.add_dependency("public_suffix", ">= 0")

  s.add_development_dependency("activerecord", ">= 3.0.0")
  s.add_development_dependency("diff-lcs", ">= 1.1.2")
  s.add_development_dependency("rake", ">= 11.0")
  s.add_development_dependency("rspec", "~> 3")
  s.add_development_dependency("sqlite3", ">= 0")
end
