name: Run tests

on: [push, pull_request]

jobs:
  test:
    name: "Run tests for ${{matrix.ruby}}"
    if: "! contains(toJSON(github.event.commits.latest.message), '[skip ci]')"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.3", "2.4", "2.5", "2.6", "2.7", "3.0", "3.1", "3.2", ruby-head]

    steps:
    - uses: actions/checkout@v3
    - name: Remove Gemfile.lock
      run: |
        rm Gemfile.lock
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true # 'bundle install' and cache gems
        ruby-version: ${{ matrix.ruby }}
    - name: Run tests
      run: bundle exec rake
